{ 
  config,
  pkgs,
  ... 
} @ inputs: {

  imports =
    [
      ../../../../common-home.nix
    ];

  home = {
    username = "squeakbug";
    homeDirectory = "/home/squeakbug";
    packages = [
      pkgs.firefox
    ];
    file = {

    };
    sessionVariables = {
      # Hint Electron apps to use Wayland:
      NIXOS_OZONE_WL = "1";
    };
  };

  programs = {
    alacritty.enable = true;
		vscode = {
      enable = true;
      package = pkgs.vscodium;
    };
    git = {
			enable = true;
			userName = "squeakbug";
			userEmail = "squeakbug73@outlook.ru";
		};
    kitty.enable = true;
  };

  services = {
		dunst.enable = true;
    # https://wiki.archlinux.org/title/Greetd
    # greetd = {
    #   enable = true;
    #   settings = {
    #     default_session = {
    #       user = "squeakbug";
    #       # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
    #       # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
    #       command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
    #       # command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd $HOME/.wayland-session";  # start wayland session with a TUI login manager
    #     };
    #   };
    # };
	};

  wayland.windowManager.hyprland = {
    enable = true;
    package = pkgs.hyprland;
    settings = {
      general = {
        gaps_in = 0;
        gaps_out = 0;
        border_size = 20;
      };
    };
  };
}
